-- 016 — GPS transportista: disponible + posición en viaje activo

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_available BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS last_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS location_updated_at TIMESTAMPTZ;

ALTER TABLE matches
  ADD COLUMN IF NOT EXISTS track_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS track_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS track_updated_at TIMESTAMPTZ;
